---

- name: 'Manage Opsi using Ansible :)'
  hosts: [ 'ypid_service_opsi' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: ypid.opsi
      tags: [ 'role::opsi' ]
